# Generated by Django 2.1.2 on 2018-12-05 00:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Time (milliseconds)')),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('classifications', models.ManyToManyField(to='ensemble.Classification')),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensemble.Model')),
            ],
        ),
        migrations.CreateModel(
            name='AudioPrediction',
            fields=[
                ('audiolabel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ensemble.AudioLabel')),
                ('confidence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensemble.ModelVersion')),
            ],
            options={
                'abstract': False,
            },
            bases=('ensemble.audiolabel', models.Model),
        ),
        migrations.CreateModel(
            name='ImagePrediction',
            fields=[
                ('imagelabel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ensemble.ImageLabel')),
                ('confidence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensemble.ModelVersion')),
            ],
            options={
                'abstract': False,
            },
            bases=('ensemble.imagelabel', models.Model),
        ),
        migrations.CreateModel(
            name='VideoLabel',
            fields=[
                ('imagelabel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ensemble.ImageLabel')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Time (milliseconds)')),
            ],
            options={
                'abstract': False,
            },
            bases=('ensemble.imagelabel',),
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensemble.Classification'),
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensemble.MediaFile'),
        ),
        migrations.AddField(
            model_name='audiolabel',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensemble.Classification'),
        ),
        migrations.AddField(
            model_name='audiolabel',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensemble.MediaFile'),
        ),
        migrations.CreateModel(
            name='VideoPrediction',
            fields=[
                ('videolabel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ensemble.VideoLabel')),
                ('confidence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensemble.ModelVersion')),
            ],
            options={
                'abstract': False,
            },
            bases=('ensemble.videolabel', models.Model),
        ),
    ]
