# Generated by Django 2.1.2 on 2018-12-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0002_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
