# Generated by Django 2.1.2 on 2018-12-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0003_auto_20181205_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioprediction',
            old_name='model',
            new_name='model_version',
        ),
        migrations.RenameField(
            model_name='imageprediction',
            old_name='model',
            new_name='model_version',
        ),
        migrations.RenameField(
            model_name='videoprediction',
            old_name='model',
            new_name='model_version',
        ),
    ]
