# Generated by Django 2.1.2 on 2018-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0004_auto_20181205_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolabel',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
