# Generated by Django 2.1.2 on 2018-12-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0006_auto_20181206_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiolabel',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
