# Generated by Django 2.1.2 on 2018-12-07 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0008_model_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='create_date',
        ),
    ]
