# Generated by Django 2.1.2 on 2018-12-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensemble', '0009_remove_model_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
